### ISSUE TITLE
ObjectFilter drops task-level options

### ISSUE THREAD

**Issue by igorraush** [joeytrapp/grunt-focus#2]
If I configure the `focus` task to `include` some watch targets, then all keys from the `watch` config which are not present in the array are dropped. This means that only target-level options can be used, task-level options are dropped.

Depending on how generic you'd like to keep `ObjectFilter`, we can either automatically push `"options"` into the `include` config, or add another option to `ObjectFilter` which will preserve/ignore certain keys.

**Comment by joeytrapp** [comment]
If I understand correctly (I don't use grunt much anymore), the task options hash does not carry over to the reset watch task. I think the assumption should be that the task options will carry over as is to the filtered version.

Seems this would be best implemented in the task. When it `get`s the watch config, it should cache the options hash. If the options hash exists (it is truthy) just add it back to the new filtered hash before setting it to the watch config.

Feel free to send a pr and I'll get it merged.
